{{- if .Values.gatewayApi.enabled -}}
{{- $fullName := include "headscale.fullname" . -}}
{{- $svcPort := .Values.service.httpPort -}}
{{- $grpcPort := .Values.service.grpcPort -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.gatewayApi.httpRoute.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- else }}
      namespace: {{ $.Release.Namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
  hostnames:
    {{- range .Values.gatewayApi.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
{{- end }}
---
{{- if and .Values.gatewayApi.enabled .Values.gatewayApi.grpcRoute.enabled -}}
{{- $fullName := include "headscale.fullname" . -}}
{{- $grpcPort := .Values.service.grpcPort -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $fullName }}-grpc
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc
spec:
  parentRefs:
    {{- range .Values.gatewayApi.grpcRoute.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- else }}
      namespace: {{ $.Release.Namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
  hostnames:
    {{- range .Values.gatewayApi.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $grpcPort }}
{{- end }}
---
{{- if and .Values.gatewayApi.enabled .Values.gatewayApi.tlsRoute.enabled -}}
{{- $fullName := include "headscale.fullname" . -}}
{{- $grpcPort := .Values.service.grpcPort -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ $fullName }}-tls
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
spec:
  parentRefs:
    {{- range .Values.gatewayApi.tlsRoute.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- else }}
      namespace: {{ $.Release.Namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
  hostnames:
    {{- range .Values.gatewayApi.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $grpcPort }}
{{- end }}
